#!/bin/sh
rm -f ./*~
rm -f ./*backup
rm -f ./*aux
rm -f ./*idx
rm -f ./*log
rm -f ./*lot
rm -f ./*out
rm -f ./*toc
rm -f ./*bbl
rm -f ./*blg
rm -f ./*lof
rm -f ./*brf
rm -f ./*glo
rm -f ./*gls
rm -f ./*ilg
rm -f ./*ind
rm -f ./*snm
rm -f ./*nav

